parameters:
    svyaznoy_auth.site_token_endpoint: '%env(resolve:SVYAZNOY_API_AUTH_ENDPOINT)%'
    svyaznoy_auth.site_token_info_endpoint: '%env(resolve:SVYAZNOY_API_AUTH_INFO_ENDPOINT)%'
    svyaznoy_auth.site_admin_endpoint: '%env(resolve:SVYAZNOY_API_ADMIN_ENDPOINT)%'
    svyaznoy_auth.site_find_by_email_endpoint: '%env(resolve:SVYAZNOY_API_EMAIL_SEARCH_ENDPOINT)%'
    svyaznoy_auth.http_proxy: '%env(resolve:REVO_PROXY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Svyaznoy\Bundle\AuthBundle\:
        resource: '../../*'
        exclude: '../../{Tests,Repository,Kernel.php}'

    Svyaznoy\Bundle\AuthBundle\Repository\SiteTokenRepository:
        arguments:
            $tokenUrl: '%svyaznoy_auth.site_token_endpoint%'
            $tokenInfoUrl: '%svyaznoy_auth.site_token_info_endpoint%'
            $proxy: '%svyaznoy_auth.http_proxy%'

    Svyaznoy\Bundle\AuthBundle\Repository\UserRepository:
        autowire: true
        arguments:
            $entityClass: 'Svyaznoy\Bundle\AuthBundle\Entity\User'
        tags: ['doctrine.repository_service']

    Svyaznoy\Bundle\AuthBundle\Repository\UserGroupRepository:
        arguments:
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - Svyaznoy\Bundle\AuthBundle\Entity\UserGroup

    Svyaznoy\Bundle\AuthBundle\Repository\AccessRightRepository:
        arguments:
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - Svyaznoy\Bundle\AuthBundle\Entity\AccessRight

    is.user:
        class: Svyaznoy\Bundle\AuthBundle\Service\SiteUserService
        arguments:
            $endpoint: '%svyaznoy_auth.site_admin_endpoint%'
            $findByEmailEndpoint: '%svyaznoy_auth.site_find_by_email_endpoint%'
            $proxy: '%svyaznoy_auth.http_proxy%'
