Svyaznoy\Bundle\AuthBundle\Entity\AccessRight:
    type: entity
    repositoryClass: Svyaznoy\Bundle\AuthBundle\Repository\AccessRightRepository
    table: access_right
    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }
    fields:
        attribute:
            type: string
            length: 80
            nullable: false
        subject:
            type: string
            length: 80
            nullable: true
        tags:
            type: string
            length: 128
            nullable: true
        description:
            type: string
            length: 128
            nullable: true
        deleted:
            type: boolean
            nullable: falsee
            options:
                unsigned: true
    manyToMany:
        groups:
            targetEntity: Svyaznoy\Bundle\AuthBundle\Entity\UserGroup
            joinTable:
                name: access_right_groups
                joinColumns:
                    access_right_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_group_id:
                        referencedColumnName: id
