Svyaznoy\Bundle\AuthBundle\Entity\User:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }
    fields:
        login:
            type: string
            length: 50
            nullable: false
            unique: true
        email:
            type: string
            length: 50
            nullable: false
            options:
                comment: User email
        sbrLogin:
            type: string
            length: 50
            nullable: true
        isUid:
            type: string
            length: 50
            nullable: false
        firstName:
            type: string
            length: 80
            nullable: true
        lastName:
            type: string
            length: 80
            nullable: true
        middleName:
            type: string
            length: 80
            nullable: true
        mobilePhone:
            type: string
            length: 10
            nullable: true
        workPhone:
            type: string
            length: 10
            nullable: true
        employmentPosition:
            type: string
            length: 400
            nullable: true
        region:
            type: string
            length: 400
            nullable: true
        deleted:
            type: boolean
            nullable: false
            options:
                unsigned: true
        salespointId:
            type: integer
            nullable: false
            options:
                unsigned: true
        password:
            type: string
            length: 50
            nullable: false
            options:
                comment: WSO2IS & SBR pass
        sbrPassword:
            type: string
            length: 150
            nullable: true
        type:
            string: string
            columnDefinition: ENUM(Widget, Seller, PartnerAdmin,PartnerManager)
            nullable: true
    manyToOne:
        group:
            targetEntity: Svyaznoy\Bundle\AuthBundle\Entity\UserGroup
            inversedBy: users
            fetch: EAGER
