Svyaznoy\Bundle\AuthBundle\Entity\UserGroup:
    type: entity
    repositoryClass: Svyaznoy\Bundle\AuthBundle\Repository\UserGroupRepository
    table: user_group
    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }
    fields:
        name:
            type: string
            length: 80
            nullable: false
        deleted:
            type: boolean
            nullable: falsee
            options:
                unsigned: true
    oneToMany:
        users:
            targetEntity: Svyaznoy\Bundle\AuthBundle\Entity\User
            mappedBy: group
            fetch: LAZY
            cascade: ["persist"]
    manyToMany:
        accessRights:
            targetEntity: Svyaznoy\Bundle\AuthBundle\Entity\AccessRight
            joinTable:
                name: access_right_groups
                joinColumns:
                    user_group_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    access_right_id:
                        referencedColumnName: id
